version: '3'

services:
  a2_1:
    build:
      context: docker/
      dockerfile: Dockerfile.a2
    volumes:
      - ./src:/usr/src/myapp

  a2_2:
    build:
      context: docker/
      dockerfile: Dockerfile.a2
    volumes:
      - ./src:/usr/src/myapp